apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-01
  namespace: qa-challenge-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-01
  template:
    metadata:
      labels:
        app: web-01
    spec:
      containers:
        - name: nginx
          image: ngnix:1.27
          ports:
            - containerPort: 80
