apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-nginx
  template:
    metadata:
      labels:
        app: qa-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
