apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-readiness
  namespace: qa-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-readiness
  template:
    metadata:
      labels:
        app: bad-readiness
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
