apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-liveness
  namespace: qa-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-liveness
  template:
    metadata:
      labels:
        app: bad-liveness
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /broken
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 2
